// ============================================================
// MovieMood Prompts Database
// AI looks here FIRST before calling Gemini API
// Format: "query" -> { company_id | genres | search_query, year_from?, year_to? }
// ============================================================

export const promptsDB = {

  // ══════════════════════════════════════════════
  // STUDIOS & COMPANIES
  // ══════════════════════════════════════════════
  "pixar": { company_id: 3 },
  "pixar movies": { company_id: 3 },
  "pixar films": { company_id: 3 },
  "pixar cartoons": { company_id: 3 },
  "pixar animated": { company_id: 3 },
  "classic pixar": { company_id: 3, year_from: 1995, year_to: 2010 },
  "new pixar": { company_id: 3, year_from: 2015, year_to: 2025 },

  "disney": { company_id: 2 },
  "disney movies": { company_id: 2 },
  "disney animated": { company_id: 2 },
  "disney classics": { company_id: 2, year_from: 1937, year_to: 1999 },
  "old disney": { company_id: 2, year_from: 1937, year_to: 1999 },
  "classic disney": { company_id: 2, year_from: 1937, year_to: 1999 },
  "disney princess": { company_id: 2, genres: [16, 10751] },
  "new disney": { company_id: 2, year_from: 2010, year_to: 2025 },
  "disney live action": { company_id: 2 },
  "walt disney": { company_id: 2 },

  "marvel": { company_id: 420 },
  "marvel movies": { company_id: 420 },
  "marvel films": { company_id: 420 },
  "mcu": { company_id: 420 },
  "avengers": { search_query: "avengers" },
  "iron man": { search_query: "iron man" },
  "spider-man": { search_query: "spider-man" },
  "spiderman": { search_query: "spider-man" },
  "thor": { search_query: "thor marvel" },
  "captain america": { search_query: "captain america" },
  "black panther": { search_query: "black panther" },
  "guardians of the galaxy": { search_query: "guardians of the galaxy" },
  "doctor strange": { search_query: "doctor strange" },
  "black widow": { search_query: "black widow" },
  "ant-man": { search_query: "ant-man" },

  "dc": { company_id: 9993 },
  "dc movies": { company_id: 9993 },
  "dc films": { company_id: 9993 },
  "dc comics": { company_id: 9993 },
  "batman": { search_query: "batman" },
  "superman": { search_query: "superman" },
  "wonder woman": { search_query: "wonder woman" },
  "justice league": { search_query: "justice league" },
  "aquaman": { search_query: "aquaman" },
  "the flash": { search_query: "the flash dc" },
  "joker": { search_query: "joker" },

  "studio ghibli": { company_id: 10342 },
  "ghibli": { company_id: 10342 },
  "ghibli movies": { company_id: 10342 },
  "miyazaki": { company_id: 10342 },
  "hayao miyazaki": { company_id: 10342 },
  "spirited away": { search_query: "spirited away" },
  "my neighbor totoro": { search_query: "my neighbor totoro" },
  "princess mononoke": { search_query: "princess mononoke" },
  "howls moving castle": { search_query: "howl's moving castle" },
  "nausicaa": { search_query: "nausicaa" },
  "castle in the sky": { search_query: "castle in the sky" },
  "kiki's delivery service": { search_query: "kiki's delivery service" },

  "dreamworks": { company_id: 521 },
  "dreamworks animation": { company_id: 521 },
  "shrek": { search_query: "shrek" },
  "kung fu panda": { search_query: "kung fu panda" },
  "how to train your dragon": { search_query: "how to train your dragon" },
  "httyd": { search_query: "how to train your dragon" },
  "madagascar": { search_query: "madagascar" },
  "the croods": { search_query: "the croods" },
  "trolls": { search_query: "trolls" },
  "bee movie": { search_query: "bee movie" },

  "illumination": { company_id: 6704 },
  "minions": { search_query: "minions" },
  "despicable me": { search_query: "despicable me" },
  "the secret life of pets": { search_query: "secret life of pets" },
  "sing": { search_query: "sing illumination" },

  "a24": { company_id: 41077 },
  "a24 movies": { company_id: 41077 },
  "a24 films": { company_id: 41077 },
  "a24 horror": { company_id: 41077, genres: [27] },

  "blumhouse": { company_id: 3172 },
  "blumhouse horror": { company_id: 3172 },
  "blumhouse movies": { company_id: 3172 },

  "warner bros": { company_id: 174 },
  "universal": { company_id: 33 },
  "paramount": { company_id: 4 },
  "sony pictures": { company_id: 5 },
  "lionsgate": { company_id: 1632 },
  "miramax": { company_id: 14 },

  // ══════════════════════════════════════════════
  // FRANCHISES
  // ══════════════════════════════════════════════
  "star wars": { search_query: "star wars" },
  "star wars movies": { search_query: "star wars" },
  "harry potter": { search_query: "harry potter" },
  "hogwarts": { search_query: "harry potter" },
  "fantastic beasts": { search_query: "fantastic beasts" },
  "lord of the rings": { search_query: "lord of the rings" },
  "lotr": { search_query: "lord of the rings" },
  "the hobbit": { search_query: "the hobbit" },
  "tolkien": { search_query: "tolkien" },
  "james bond": { search_query: "james bond" },
  "007": { search_query: "james bond" },
  "mission impossible": { search_query: "mission impossible" },
  "fast and furious": { search_query: "fast furious" },
  "fast furious": { search_query: "fast furious" },
  "jurassic park": { search_query: "jurassic park" },
  "jurassic world": { search_query: "jurassic world" },
  "indiana jones": { search_query: "indiana jones" },
  "terminator": { search_query: "terminator" },
  "alien": { search_query: "alien" },
  "aliens": { search_query: "aliens" },
  "john wick": { search_query: "john wick" },
  "matrix": { search_query: "matrix" },
  "the matrix": { search_query: "matrix" },
  "halloween": { search_query: "halloween" },
  "nightmare on elm street": { search_query: "nightmare elm street" },
  "freddy krueger": { search_query: "nightmare elm street" },
  "friday the 13th": { search_query: "friday 13th" },
  "jason voorhees": { search_query: "friday 13th" },
  "saw": { search_query: "saw" },
  "conjuring": { search_query: "conjuring" },
  "the conjuring": { search_query: "conjuring" },
  "hunger games": { search_query: "hunger games" },
  "twilight": { search_query: "twilight" },
  "pirates of the caribbean": { search_query: "pirates of the caribbean" },
  "transformers": { search_query: "transformers" },
  "x-men": { search_query: "x-men" },
  "xmen": { search_query: "x-men" },
  "toy story": { search_query: "toy story" },
  "finding nemo": { search_query: "finding nemo" },
  "finding dory": { search_query: "finding dory" },
  "the incredibles": { search_query: "incredibles" },
  "incredibles": { search_query: "incredibles" },
  "ice age": { search_query: "ice age" },
  "hotel transylvania": { search_query: "hotel transylvania" },
  "moana": { search_query: "moana" },
  "frozen": { search_query: "frozen" },
  "coco": { search_query: "coco pixar" },
  "wall-e": { search_query: "wall-e" },
  "up": { search_query: "up pixar" },
  "ratatouille": { search_query: "ratatouille" },
  "inside out": { search_query: "inside out pixar" },
  "soul": { search_query: "soul pixar" },
  "brave": { search_query: "brave pixar" },
  "monsters inc": { search_query: "monsters inc" },
  "encanto": { search_query: "encanto" },
  "turning red": { search_query: "turning red" },
  "luca": { search_query: "luca pixar" },
  "elemental": { search_query: "elemental pixar" },
  "zootopia": { search_query: "zootopia" },
  "tangled": { search_query: "tangled" },
  "big hero 6": { search_query: "big hero 6" },
  "wreck it ralph": { search_query: "wreck-it ralph" },

  // ══════════════════════════════════════════════
  // DIRECTORS
  // ══════════════════════════════════════════════
  "nolan": { search_query: "christopher nolan" },
  "christopher nolan": { search_query: "christopher nolan" },
  "nolan movies": { search_query: "christopher nolan" },
  "nolan films": { search_query: "christopher nolan" },
  "tarantino": { search_query: "quentin tarantino" },
  "quentin tarantino": { search_query: "quentin tarantino" },
  "kubrick": { search_query: "stanley kubrick" },
  "stanley kubrick": { search_query: "stanley kubrick" },
  "spielberg": { search_query: "steven spielberg" },
  "steven spielberg": { search_query: "steven spielberg" },
  "scorsese": { search_query: "martin scorsese" },
  "martin scorsese": { search_query: "martin scorsese" },
  "fincher": { search_query: "david fincher" },
  "david fincher": { search_query: "david fincher" },
  "lynch": { search_query: "david lynch" },
  "david lynch": { search_query: "david lynch" },
  "villeneuve": { search_query: "denis villeneuve" },
  "denis villeneuve": { search_query: "denis villeneuve" },
  "wes anderson": { search_query: "wes anderson" },
  "tim burton": { search_query: "tim burton" },
  "james cameron": { search_query: "james cameron" },
  "ridley scott": { search_query: "ridley scott" },
  "hitchcock": { search_query: "alfred hitchcock" },
  "alfred hitchcock": { search_query: "alfred hitchcock" },
  "coppola": { search_query: "francis ford coppola" },
  "francis ford coppola": { search_query: "francis ford coppola" },
  "peter jackson": { search_query: "peter jackson" },
  "guillermo del toro": { search_query: "guillermo del toro" },
  "del toro": { search_query: "guillermo del toro" },
  "darren aronofsky": { search_query: "darren aronofsky" },
  "aronofsky": { search_query: "darren aronofsky" },
  "sofia coppola": { search_query: "sofia coppola" },
  "wong kar-wai": { search_query: "wong kar-wai" },
  "bong joon-ho": { search_query: "bong joon-ho" },
  "bong": { search_query: "bong joon-ho" },
  "kurosawa": { search_query: "akira kurosawa" },
  "akira kurosawa": { search_query: "akira kurosawa" },
  "ingmar bergman": { search_query: "ingmar bergman" },
  "bergman": { search_query: "ingmar bergman" },
  "fellini": { search_query: "federico fellini" },
  "federico fellini": { search_query: "federico fellini" },
  "paul thomas anderson": { search_query: "paul thomas anderson" },
  "pta": { search_query: "paul thomas anderson" },
  "coen brothers": { search_query: "coen brothers" },
  "woody allen": { search_query: "woody allen" },
  "terry gilliam": { search_query: "terry gilliam" },
  "robert zemeckis": { search_query: "robert zemeckis" },
  "zemeckis": { search_query: "robert zemeckis" },
  "ron howard": { search_query: "ron howard" },
  "oliver stone": { search_query: "oliver stone" },
  "park chan-wook": { search_query: "park chan-wook" },
  "zhang yimou": { search_query: "zhang yimou" },
  "ang lee": { search_query: "ang lee" },
  "sam raimi": { search_query: "sam raimi" },
  "raimi": { search_query: "sam raimi" },
  "christopher nolan early films": { search_query: "christopher nolan", year_from: 1998, year_to: 2006 },

  // ══════════════════════════════════════════════
  // ACTORS & ACTRESSES
  // ══════════════════════════════════════════════
  "tom hanks": { search_query: "tom hanks" },
  "tom hanks movies": { search_query: "tom hanks" },
  "leonardo dicaprio": { search_query: "leonardo dicaprio" },
  "dicaprio": { search_query: "leonardo dicaprio" },
  "leo dicaprio": { search_query: "leonardo dicaprio" },
  "brad pitt": { search_query: "brad pitt" },
  "morgan freeman": { search_query: "morgan freeman" },
  "meryl streep": { search_query: "meryl streep" },
  "cate blanchett": { search_query: "cate blanchett" },
  "natalie portman": { search_query: "natalie portman" },
  "scarlett johansson": { search_query: "scarlett johansson" },
  "ryan gosling": { search_query: "ryan gosling" },
  "gosling": { search_query: "ryan gosling" },
  "joaquin phoenix": { search_query: "joaquin phoenix" },
  "christian bale": { search_query: "christian bale" },
  "matt damon": { search_query: "matt damon" },
  "robert de niro": { search_query: "robert de niro" },
  "de niro": { search_query: "robert de niro" },
  "al pacino": { search_query: "al pacino" },
  "pacino": { search_query: "al pacino" },
  "denzel washington": { search_query: "denzel washington" },
  "denzel": { search_query: "denzel washington" },
  "will smith": { search_query: "will smith" },
  "johnny depp": { search_query: "johnny depp" },
  "depp": { search_query: "johnny depp" },
  "keanu reeves": { search_query: "keanu reeves" },
  "keanu": { search_query: "keanu reeves" },
  "samuel l jackson": { search_query: "samuel l jackson" },
  "bruce willis": { search_query: "bruce willis" },
  "sylvester stallone": { search_query: "sylvester stallone" },
  "stallone": { search_query: "sylvester stallone" },
  "arnold schwarzenegger": { search_query: "arnold schwarzenegger" },
  "schwarzenegger": { search_query: "arnold schwarzenegger" },
  "arnie": { search_query: "arnold schwarzenegger" },
  "tom cruise": { search_query: "tom cruise" },
  "harrison ford": { search_query: "harrison ford" },
  "clint eastwood": { search_query: "clint eastwood" },
  "eastwood": { search_query: "clint eastwood" },
  "emma stone": { search_query: "emma stone" },
  "jennifer lawrence": { search_query: "jennifer lawrence" },
  "anne hathaway": { search_query: "anne hathaway" },
  "charlize theron": { search_query: "charlize theron" },
  "timothee chalamet": { search_query: "timothée chalamet" },
  "chalamet": { search_query: "timothée chalamet" },
  "florence pugh": { search_query: "florence pugh" },
  "zendaya": { search_query: "zendaya" },
  "pedro pascal": { search_query: "pedro pascal" },
  "adam driver": { search_query: "adam driver" },
  "margot robbie": { search_query: "margot robbie" },
  "cillian murphy": { search_query: "cillian murphy" },
  "paul mescal": { search_query: "paul mescal" },
  "austin butler": { search_query: "austin butler" },
  "andrew garfield": { search_query: "andrew garfield" },
  "tom holland": { search_query: "tom holland" },
  "robert pattinson": { search_query: "robert pattinson" },
  "pattinson": { search_query: "robert pattinson" },
  "dwayne johnson": { search_query: "dwayne johnson" },
  "the rock": { search_query: "dwayne johnson" },
  "chris pratt": { search_query: "chris pratt" },
  "chris hemsworth": { search_query: "chris hemsworth" },
  "chris evans": { search_query: "chris evans" },
  "robert downey jr": { search_query: "robert downey" },
  "rdj": { search_query: "robert downey" },
  "vin diesel": { search_query: "vin diesel" },
  "liam neeson": { search_query: "liam neeson" },
  "neeson": { search_query: "liam neeson" },
  "russell crowe": { search_query: "russell crowe" },
  "colin farrell": { search_query: "colin farrell" },
  "benedict cumberbatch": { search_query: "benedict cumberbatch" },
  "cumberbatch": { search_query: "benedict cumberbatch" },
  "daniel craig": { search_query: "daniel craig" },
  "idris elba": { search_query: "idris elba" },
  "jake gyllenhaal": { search_query: "jake gyllenhaal" },
  "gyllenhaal": { search_query: "jake gyllenhaal" },
  "oscar isaac": { search_query: "oscar isaac" },
  "michael fassbender": { search_query: "michael fassbender" },
  "viola davis": { search_query: "viola davis" },
  "lupita nyongo": { search_query: "lupita nyong'o" },
  "chadwick boseman": { search_query: "chadwick boseman" },
  "angela bassett": { search_query: "angela bassett" },
  "halle berry": { search_query: "halle berry" },
  "nicole kidman": { search_query: "nicole kidman" },
  "julia roberts": { search_query: "julia roberts" },
  "reese witherspoon": { search_query: "reese witherspoon" },
  "cate winslet": { search_query: "kate winslet" },
  "kate winslet": { search_query: "kate winslet" },
  "gwyneth paltrow": { search_query: "gwyneth paltrow" },
  "judi dench": { search_query: "judi dench" },
  "helen mirren": { search_query: "helen mirren" },
  "gary oldman": { search_query: "gary oldman" },
  "anthony hopkins": { search_query: "anthony hopkins" },
  "hopkins": { search_query: "anthony hopkins" },
  "jack nicholson": { search_query: "jack nicholson" },
  "nicholson": { search_query: "jack nicholson" },
  "dustin hoffman": { search_query: "dustin hoffman" },
  "gene hackman": { search_query: "gene hackman" },
  "robert redford": { search_query: "robert redford" },
  "paul newman": { search_query: "paul newman" },
  "marlon brando": { search_query: "marlon brando" },
  "brando": { search_query: "marlon brando" },
  "humphrey bogart": { search_query: "humphrey bogart" },
  "bogart": { search_query: "humphrey bogart" },
  "james dean": { search_query: "james dean" },
  "audrey hepburn": { search_query: "audrey hepburn" },
  "grace kelly": { search_query: "grace kelly" },
  "marilyn monroe": { search_query: "marilyn monroe" },
  "clint eastwood actor": { search_query: "clint eastwood" },

  // ══════════════════════════════════════════════
  // NATIONAL CINEMAS
  // ══════════════════════════════════════════════
  "korean": { search_query: "korean" },
  "korean movies": { search_query: "korean" },
  "korean drama": { search_query: "korean" },
  "k-drama": { search_query: "korean" },
  "k-movie": { search_query: "korean" },
  "korean horror": { search_query: "korean horror" },
  "korean thriller": { search_query: "korean thriller" },
  "korean romance": { search_query: "korean romance" },
  "korean action": { search_query: "korean action" },
  "parasite": { search_query: "parasite bong" },
  "oldboy": { search_query: "oldboy" },
  "train to busan": { search_query: "train to busan" },
  "the wailing": { search_query: "the wailing" },
  "squid game": { search_query: "squid game" },

  "japanese": { search_query: "japanese" },
  "japanese movies": { search_query: "japanese" },
  "japanese anime": { search_query: "anime" },
  "j-drama": { search_query: "japanese drama" },
  "japanese horror": { search_query: "japanese horror" },
  "japanese thriller": { search_query: "japanese thriller" },
  "ringu": { search_query: "ring japanese" },
  "akira": { search_query: "akira anime" },

  "french": { search_query: "french" },
  "french movies": { search_query: "french" },
  "french cinema": { search_query: "french" },
  "french romance": { search_query: "french romance" },
  "french comedy": { search_query: "french comedy" },
  "french thriller": { search_query: "french thriller" },
  "french horror": { search_query: "french horror" },
  "new french extremity": { search_query: "french horror extreme" },
  "french new wave": { search_query: "french new wave cinema" },

  "italian": { search_query: "italian" },
  "italian cinema": { search_query: "italian" },
  "italian movies": { search_query: "italian" },
  "spaghetti western": { genres: [37], search_query: "spaghetti western" },
  "italian horror": { search_query: "italian horror" },

  "spanish": { search_query: "spanish" },
  "spanish movies": { search_query: "spanish" },
  "spanish horror": { search_query: "spanish horror" },

  "german": { search_query: "german" },
  "german cinema": { search_query: "german" },
  "german movies": { search_query: "german" },

  "bollywood": { search_query: "bollywood" },
  "indian movies": { search_query: "bollywood" },
  "indian cinema": { search_query: "bollywood" },
  "hindi movies": { search_query: "hindi" },
  "old bollywood": { search_query: "bollywood", year_from: 1970, year_to: 2000 },
  "classic bollywood": { search_query: "bollywood", year_from: 1950, year_to: 1990 },
  "new bollywood": { search_query: "bollywood", year_from: 2010, year_to: 2025 },
  "bollywood romance": { search_query: "bollywood romance" },
  "bollywood action": { search_query: "bollywood action" },

  "chinese": { search_query: "chinese" },
  "chinese cinema": { search_query: "chinese" },
  "chinese movies": { search_query: "chinese" },
  "kung fu movies": { search_query: "kung fu" },
  "hong kong": { search_query: "hong kong" },

  "turkish": { search_query: "turkish" },
  "turkish drama": { search_query: "turkish drama" },
  "turkish movies": { search_query: "turkish" },

  "russian": { search_query: "russian" },
  "russian cinema": { search_query: "russian" },
  "russian movies": { search_query: "russian" },
  "soviet cinema": { search_query: "soviet film", year_from: 1950, year_to: 1991 },

  "scandinavian": { search_query: "scandinavian" },
  "nordic": { search_query: "nordic film" },
  "swedish movies": { search_query: "swedish film" },
  "danish movies": { search_query: "danish film" },
  "norwegian movies": { search_query: "norwegian film" },

  "iranian": { search_query: "iranian" },
  "iranian cinema": { search_query: "iranian" },
  "polish": { search_query: "polish film" },
  "ukrainian": { search_query: "ukrainian film" },
  "latin american": { search_query: "latin american film" },
  "mexican": { search_query: "mexican film" },
  "argentinian": { search_query: "argentinian film" },
  "brazilian": { search_query: "brazilian film" },

  // ══════════════════════════════════════════════
  // GENRES — PURE
  // ══════════════════════════════════════════════
  "action": { genres: [28] },
  "action movies": { genres: [28] },
  "action films": { genres: [28] },
  "adventure": { genres: [12] },
  "adventure movies": { genres: [12] },
  "animation": { genres: [16] },
  "animated": { genres: [16] },
  "animated movies": { genres: [16] },
  "cartoons": { genres: [16] },
  "comedy": { genres: [35] },
  "comedies": { genres: [35] },
  "comedy movies": { genres: [35] },
  "crime": { genres: [80] },
  "crime movies": { genres: [80] },
  "documentary": { genres: [99] },
  "documentaries": { genres: [99] },
  "drama": { genres: [18] },
  "dramas": { genres: [18] },
  "family": { genres: [10751] },
  "family movies": { genres: [10751] },
  "family films": { genres: [10751] },
  "fantasy": { genres: [14] },
  "fantasy movies": { genres: [14] },
  "history": { genres: [36] },
  "historical": { genres: [36, 18] },
  "horror": { genres: [27] },
  "horror movies": { genres: [27] },
  "horror films": { genres: [27] },
  "music": { genres: [10402] },
  "musical": { genres: [10402] },
  "mystery": { genres: [9648] },
  "mystery movies": { genres: [9648] },
  "romance": { genres: [10749] },
  "romantic": { genres: [10749, 35] },
  "romance movies": { genres: [10749] },
  "sci-fi": { genres: [878] },
  "scifi": { genres: [878] },
  "science fiction": { genres: [878] },
  "thriller": { genres: [53] },
  "thrillers": { genres: [53] },
  "war": { genres: [10752] },
  "war movies": { genres: [10752] },
  "western": { genres: [37] },
  "westerns": { genres: [37] },
  "western movies": { genres: [37] },

  // ══════════════════════════════════════════════
  // GENRE COMBINATIONS
  // ══════════════════════════════════════════════
  "romantic comedy": { genres: [10749, 35] },
  "romcom": { genres: [10749, 35] },
  "rom com": { genres: [10749, 35] },
  "action comedy": { genres: [28, 35] },
  "horror comedy": { genres: [27, 35] },
  "dark comedy": { genres: [35, 80] },
  "black comedy": { genres: [35, 80] },
  "crime comedy": { genres: [80, 35] },
  "sci-fi thriller": { genres: [878, 53] },
  "sci fi thriller": { genres: [878, 53] },
  "crime thriller": { genres: [80, 53] },
  "psychological thriller": { genres: [53, 9648] },
  "action thriller": { genres: [28, 53] },
  "romantic drama": { genres: [10749, 18] },
  "crime drama": { genres: [80, 18] },
  "historical drama": { genres: [36, 18] },
  "fantasy adventure": { genres: [14, 12] },
  "action adventure": { genres: [28, 12] },
  "supernatural horror": { genres: [27, 14] },
  "found footage horror": { genres: [27] },
  "slasher": { genres: [27] },
  "slasher movies": { genres: [27] },
  "survival horror": { genres: [27, 53] },
  "biopic": { genres: [18, 36] },
  "biographical": { genres: [18, 36] },
  "biographical drama": { genres: [18, 36] },
  "spy": { genres: [28, 53] },
  "spy movies": { genres: [28, 53] },
  "spy thriller": { genres: [28, 53] },
  "espionage": { genres: [28, 53] },
  "superhero": { genres: [28, 12] },
  "superhero movies": { genres: [28, 12] },
  "disaster": { genres: [28, 12] },
  "disaster movies": { genres: [28, 12] },
  "heist": { genres: [80, 53] },
  "heist movies": { genres: [80, 53] },
  "gangster": { genres: [80, 18] },
  "gangster movies": { genres: [80, 18] },
  "mafia": { genres: [80, 18] },
  "teen comedy": { genres: [35, 10751] },
  "coming of age": { genres: [18, 35] },
  "coming of age drama": { genres: [18] },
  "road movie": { genres: [12, 18] },
  "road trip": { genres: [12, 35] },
  "buddy movie": { genres: [35, 28] },
  "buddy cop": { genres: [28, 35] },
  "zombie": { genres: [27] },
  "zombie movies": { genres: [27] },
  "vampire": { genres: [27, 14] },
  "vampire movies": { genres: [27, 14] },

  // ══════════════════════════════════════════════
  // DECADES — GENRES BY ERA
  // ══════════════════════════════════════════════

  // 1930s-40s
  "1930s": { year_from: 1930, year_to: 1939 },
  "30s movies": { year_from: 1930, year_to: 1939 },
  "1940s": { year_from: 1940, year_to: 1949 },
  "40s movies": { year_from: 1940, year_to: 1949 },
  "film noir": { genres: [80, 9648], year_from: 1940, year_to: 1960 },
  "classic hollywood": { year_from: 1930, year_to: 1960 },
  "golden age hollywood": { year_from: 1930, year_to: 1960 },
  "old hollywood": { year_from: 1930, year_to: 1965 },

  // 1950s
  "50s movies": { year_from: 1950, year_to: 1959 },
  "1950s": { year_from: 1950, year_to: 1959 },
  "50s horror": { genres: [27], year_from: 1950, year_to: 1959 },
  "50s sci-fi": { genres: [878], year_from: 1950, year_to: 1959 },
  "50s westerns": { genres: [37], year_from: 1950, year_to: 1959 },
  "50s romance": { genres: [10749], year_from: 1950, year_to: 1959 },

  // 1960s
  "60s movies": { year_from: 1960, year_to: 1969 },
  "1960s": { year_from: 1960, year_to: 1969 },
  "60s horror": { genres: [27], year_from: 1960, year_to: 1969 },
  "60s comedy": { genres: [35], year_from: 1960, year_to: 1969 },
  "60s drama": { genres: [18], year_from: 1960, year_to: 1969 },
  "60s westerns": { genres: [37], year_from: 1960, year_to: 1969 },
  "60s sci-fi": { genres: [878], year_from: 1960, year_to: 1969 },
  "60s romance": { genres: [10749], year_from: 1960, year_to: 1969 },
  "60s musicals": { genres: [10402], year_from: 1960, year_to: 1969 },
  "new wave cinema": { genres: [18], year_from: 1958, year_to: 1972 },

  // 1970s
  "70s movies": { year_from: 1970, year_to: 1979 },
  "1970s": { year_from: 1970, year_to: 1979 },
  "70s horror": { genres: [27], year_from: 1970, year_to: 1979 },
  "70s action": { genres: [28], year_from: 1970, year_to: 1979 },
  "70s drama": { genres: [18], year_from: 1970, year_to: 1979 },
  "70s thriller": { genres: [53], year_from: 1970, year_to: 1979 },
  "70s crime": { genres: [80], year_from: 1970, year_to: 1979 },
  "70s sci-fi": { genres: [878], year_from: 1970, year_to: 1979 },
  "70s comedy": { genres: [35], year_from: 1970, year_to: 1979 },
  "70s romance": { genres: [10749], year_from: 1970, year_to: 1979 },
  "70s westerns": { genres: [37], year_from: 1970, year_to: 1979 },
  "grindhouse": { genres: [27, 28], year_from: 1965, year_to: 1985 },
  "blaxploitation": { genres: [28, 80], year_from: 1970, year_to: 1979 },
  "new hollywood": { genres: [18, 80], year_from: 1967, year_to: 1980 },

  // 1980s
  "80s movies": { year_from: 1980, year_to: 1989 },
  "1980s": { year_from: 1980, year_to: 1989 },
  "80s horror": { genres: [27], year_from: 1980, year_to: 1989 },
  "80s action": { genres: [28], year_from: 1980, year_to: 1989 },
  "80s action movies": { genres: [28, 12], year_from: 1980, year_to: 1989 },
  "80s comedy": { genres: [35], year_from: 1980, year_to: 1989 },
  "80s drama": { genres: [18], year_from: 1980, year_to: 1989 },
  "80s sci-fi": { genres: [878], year_from: 1980, year_to: 1989 },
  "80s thriller": { genres: [53], year_from: 1980, year_to: 1989 },
  "80s romance": { genres: [10749, 35], year_from: 1980, year_to: 1989 },
  "80s teen": { genres: [35, 18], year_from: 1980, year_to: 1989 },
  "80s adventure": { genres: [12], year_from: 1980, year_to: 1989 },
  "80s animation": { genres: [16], year_from: 1980, year_to: 1989 },
  "80s slasher": { genres: [27], year_from: 1980, year_to: 1989 },
  "80s fantasy": { genres: [14], year_from: 1980, year_to: 1989 },
  "80s war movies": { genres: [10752], year_from: 1980, year_to: 1989 },
  "80s crime": { genres: [80], year_from: 1980, year_to: 1989 },
  "retro action": { genres: [28], year_from: 1980, year_to: 1995 },

  // 1990s
  "90s movies": { year_from: 1990, year_to: 1999 },
  "1990s": { year_from: 1990, year_to: 1999 },
  "90s horror": { genres: [27], year_from: 1990, year_to: 1999 },
  "horrors of 90s": { genres: [27], year_from: 1990, year_to: 1999 },
  "horror of 90s": { genres: [27], year_from: 1990, year_to: 1999 },
  "90s action": { genres: [28], year_from: 1990, year_to: 1999 },
  "90s action movies": { genres: [28, 12], year_from: 1990, year_to: 1999 },
  "90s comedy": { genres: [35], year_from: 1990, year_to: 1999 },
  "90s drama": { genres: [18], year_from: 1990, year_to: 1999 },
  "90s sci-fi": { genres: [878], year_from: 1990, year_to: 1999 },
  "90s thriller": { genres: [53], year_from: 1990, year_to: 1999 },
  "90s romance": { genres: [10749, 35], year_from: 1990, year_to: 1999 },
  "90s teen": { genres: [35, 18], year_from: 1990, year_to: 1999 },
  "90s animation": { genres: [16], year_from: 1990, year_to: 1999 },
  "90s adventure": { genres: [12], year_from: 1990, year_to: 1999 },
  "90s crime": { genres: [80], year_from: 1990, year_to: 1999 },
  "90s fantasy": { genres: [14], year_from: 1990, year_to: 1999 },
  "90s war movies": { genres: [10752], year_from: 1990, year_to: 1999 },
  "90s slasher": { genres: [27], year_from: 1990, year_to: 1999 },
  "90s romcom": { genres: [10749, 35], year_from: 1990, year_to: 1999 },
  "90s cartoons": { genres: [16, 10751], year_from: 1990, year_to: 1999 },
  "90s family": { genres: [10751], year_from: 1990, year_to: 1999 },
  "90s classics": { year_from: 1990, year_to: 1999 },

  // 2000s
  "2000s movies": { year_from: 2000, year_to: 2009 },
  "2000s": { year_from: 2000, year_to: 2009 },
  "2000s horror": { genres: [27], year_from: 2000, year_to: 2009 },
  "2000s action": { genres: [28], year_from: 2000, year_to: 2009 },
  "2000s comedy": { genres: [35], year_from: 2000, year_to: 2009 },
  "2000s drama": { genres: [18], year_from: 2000, year_to: 2009 },
  "2000s sci-fi": { genres: [878], year_from: 2000, year_to: 2009 },
  "2000s thriller": { genres: [53], year_from: 2000, year_to: 2009 },
  "2000s romance": { genres: [10749, 35], year_from: 2000, year_to: 2009 },
  "2000s romcom": { genres: [10749, 35], year_from: 2000, year_to: 2009 },
  "2000s animation": { genres: [16], year_from: 2000, year_to: 2009 },
  "2000s teen": { genres: [35, 18], year_from: 2000, year_to: 2009 },
  "2000s crime": { genres: [80], year_from: 2000, year_to: 2009 },
  "2000s fantasy": { genres: [14, 12], year_from: 2000, year_to: 2009 },
  "early 2000s": { year_from: 2000, year_to: 2005 },

  // 2010s
  "2010s movies": { year_from: 2010, year_to: 2019 },
  "2010s": { year_from: 2010, year_to: 2019 },
  "2010s horror": { genres: [27], year_from: 2010, year_to: 2019 },
  "2010s action": { genres: [28], year_from: 2010, year_to: 2019 },
  "2010s drama": { genres: [18], year_from: 2010, year_to: 2019 },
  "2010s comedy": { genres: [35], year_from: 2010, year_to: 2019 },
  "2010s sci-fi": { genres: [878], year_from: 2010, year_to: 2019 },
  "2010s romance": { genres: [10749], year_from: 2010, year_to: 2019 },
  "2010s thriller": { genres: [53], year_from: 2010, year_to: 2019 },
  "last decade": { year_from: 2010, year_to: 2019 },

  // 2020s
  "2020s movies": { year_from: 2020, year_to: 2025 },
  "2020s": { year_from: 2020, year_to: 2025 },
  "2020s horror": { genres: [27], year_from: 2020, year_to: 2025 },
  "2020s drama": { genres: [18], year_from: 2020, year_to: 2025 },
  "recent movies": { year_from: 2022, year_to: 2025 },
  "new releases": { year_from: 2023, year_to: 2025 },
  "this year": { year_from: 2024, year_to: 2025 },
  "last year": { year_from: 2023, year_to: 2024 },
  "recent horror": { genres: [27], year_from: 2018, year_to: 2025 },
  "recent action": { genres: [28], year_from: 2018, year_to: 2025 },
  "recent drama": { genres: [18], year_from: 2018, year_to: 2025 },
  "new movies": { year_from: 2022, year_to: 2025 },
  "latest movies": { year_from: 2023, year_to: 2025 },
  "modern movies": { year_from: 2010, year_to: 2025 },
  "classic movies": { year_from: 1940, year_to: 1985 },
  "classic films": { year_from: 1940, year_to: 1985 },
  "old movies": { year_from: 1940, year_to: 1990 },
  "vintage movies": { year_from: 1940, year_to: 1985 },
  "vintage films": { year_from: 1940, year_to: 1985 },
  "retro movies": { year_from: 1960, year_to: 1990 },

  // ══════════════════════════════════════════════
  // MOODS & EMOTIONS
  // ══════════════════════════════════════════════
  "sad": { genres: [18] },
  "want to cry": { genres: [18] },
  "need to cry": { genres: [18] },
  "feel like crying": { genres: [18] },
  "something sad": { genres: [18] },
  "tearjerker": { genres: [18] },
  "emotional": { genres: [18] },
  "heartbreaking": { genres: [18] },
  "make me cry": { genres: [18] },
  "cry my eyes out": { genres: [18] },

  "happy": { genres: [35, 10749] },
  "feel good": { genres: [35, 18] },
  "feel good movie": { genres: [35, 18] },
  "uplifting": { genres: [35, 18] },
  "cheerful": { genres: [35] },
  "positive vibes": { genres: [35, 10749] },
  "wholesome": { genres: [35, 10751] },
  "something happy": { genres: [35] },
  "make me laugh": { genres: [35] },
  "need to laugh": { genres: [35] },
  "funny": { genres: [35] },
  "hilarious": { genres: [35] },
  "laugh out loud": { genres: [35] },

  "scared": { genres: [27, 53] },
  "want to be scared": { genres: [27] },
  "something scary": { genres: [27] },
  "creepy": { genres: [27, 9648] },
  "terrifying": { genres: [27] },
  "nightmare": { genres: [27] },
  "disturbing": { genres: [27, 18] },
  "unsettling": { genres: [27, 9648] },
  "dark and creepy": { genres: [27, 53] },

  "excited": { genres: [28, 12] },
  "pumped": { genres: [28] },
  "adrenaline": { genres: [28, 12] },
  "hyped": { genres: [28] },
  "intense": { genres: [28, 53] },
  "edge of seat": { genres: [53, 28] },
  "thrilling": { genres: [53] },

  "relaxed": { genres: [35, 10749] },
  "calm": { genres: [35, 10749] },
  "cozy": { genres: [35, 10749] },
  "chill": { genres: [35, 10749] },
  "cozy evening": { genres: [35, 10749] },
  "chill movie": { genres: [35, 10749] },
  "something light": { genres: [35, 10749] },
  "easy watching": { genres: [35, 10749] },
  "not too heavy": { genres: [35, 10749] },
  "easy to watch": { genres: [35, 10749] },

  "inspired": { genres: [18, 36] },
  "motivating": { genres: [18, 36] },
  "motivational": { genres: [18, 36] },
  "inspiring": { genres: [18, 36] },
  "empowering": { genres: [18, 36] },

  "nostalgic": { genres: [16, 10751] },
  "childhood": { genres: [16, 10751] },
  "childhood movies": { genres: [16, 10751] },
  "childhood favorites": { genres: [16, 10751] },
  "miss childhood": { genres: [16, 10751] },

  "thoughtful": { genres: [18, 878] },
  "philosophical": { genres: [18, 878] },
  "deep": { genres: [18, 878] },
  "something to think about": { genres: [18, 878] },
  "thought provoking": { genres: [18, 878] },
  "mind blowing": { genres: [878, 9648] },
  "mind-blowing": { genres: [878, 9648] },
  "mind bending": { genres: [878, 9648] },
  "mind-bending": { genres: [878, 9648] },
  "plot twist": { genres: [9648, 53] },
  "unpredictable": { genres: [9648, 53] },
  "keeps you guessing": { genres: [9648, 53] },
  "mindfuck": { genres: [878, 9648] },
  "complex": { genres: [9648, 18] },
  "layered": { genres: [9648, 18] },

  "adventurous": { genres: [12, 14] },
  "epic": { genres: [28, 12] },
  "something epic": { genres: [28, 12] },
  "grand": { genres: [28, 12] },
  "spectacular": { genres: [28, 12] },
  "big blockbuster": { genres: [28, 12] },

  "romantic": { genres: [10749, 35] },
  "in love": { genres: [10749] },
  "love story": { genres: [10749] },
  "lovey dovey": { genres: [10749, 35] },
  "want romance": { genres: [10749] },
  "something romantic": { genres: [10749, 35] },

  "dark": { genres: [18, 53] },
  "dark movie": { genres: [18, 53] },
  "gloomy": { genres: [18, 53] },
  "dark and gritty": { genres: [18, 80] },
  "gritty": { genres: [18, 80] },
  "brutal": { genres: [18, 28] },
  "heavy": { genres: [18, 53] },
  "serious": { genres: [18] },
  "dark and heavy": { genres: [18, 53] },

  "tense": { genres: [53] },
  "gripping": { genres: [53, 9648] },
  "suspenseful": { genres: [53] },
  "on the edge": { genres: [53, 28] },
  "cannot stop watching": { genres: [53, 9648] },
  "binge worthy": { genres: [53, 9648] },

  // ══════════════════════════════════════════════
  // SITUATIONS — VERY DETAILED
  // ══════════════════════════════════════════════

  // DATE & RELATIONSHIP
  "date night": { genres: [10749, 35] },
  "date night movie": { genres: [10749, 35] },
  "first date": { genres: [10749, 35] },
  "movie for a date": { genres: [10749, 35] },
  "with girlfriend": { genres: [10749, 35] },
  "with boyfriend": { genres: [10749, 35] },
  "with my partner": { genres: [10749, 35] },
  "romantic evening": { genres: [10749, 35] },
  "romantic night": { genres: [10749, 35] },
  "anniversary": { genres: [10749, 18] },
  "valentines day": { genres: [10749, 35] },
  "valentine": { genres: [10749, 35] },

  // BREAKUP & HEARTBREAK
  "after breakup": { genres: [18, 10749] },
  "breakup movie": { genres: [18] },
  "heartbroken": { genres: [18] },
  "got dumped": { genres: [18, 35] },
  "healing heart": { genres: [18, 10749] },
  "moving on": { genres: [18, 35] },
  "end of relationship": { genres: [18] },
  "broken heart": { genres: [18] },
  "crying over ex": { genres: [18] },
  "sad after love": { genres: [18] },
  "eat ice cream and cry": { genres: [18, 10749] },

  // FAMILY & KIDS
  "family night": { genres: [10751, 16] },
  "family movie night": { genres: [10751, 16] },
  "with kids": { genres: [10751, 16] },
  "for the whole family": { genres: [10751, 16] },
  "for kids": { genres: [10751, 16] },
  "with children": { genres: [10751, 16] },
  "with toddlers": { genres: [16, 10751] },
  "sunday family": { genres: [10751, 16] },
  "family weekend": { genres: [10751, 16] },
  "christmas family": { genres: [10751, 35] },
  "for all ages": { genres: [10751, 16] },
  "kids movies": { genres: [10751, 16] },
  "for my daughter": { genres: [10751, 16] },
  "for my son": { genres: [10751, 16] },
  "kids animation": { genres: [16, 10751] },

  // GIRLS NIGHT
  "girls night": { genres: [35, 10749] },
  "girls night out": { genres: [35, 10749] },
  "girls night in": { genres: [35, 10749] },
  "chick flick": { genres: [10749, 35] },
  "with girlfriends": { genres: [35, 10749] },
  "girls weekend": { genres: [35, 10749] },
  "bachelorette": { genres: [35, 10749] },
  "wine and movie": { genres: [35, 10749] },
  "ladies night": { genres: [35, 10749] },

  // GUYS NIGHT
  "guys night": { genres: [28, 35] },
  "boys night": { genres: [28, 35] },
  "with the bros": { genres: [28, 35] },
  "with friends": { genres: [28, 35] },
  "group movie night": { genres: [28, 35] },
  "bro movie": { genres: [28, 35] },
  "lads night": { genres: [28, 35] },
  "stag night": { genres: [28, 35] },

  // TIME OF DAY
  "morning": { genres: [35, 10749] },
  "sunday morning": { genres: [35, 10749] },
  "lazy morning": { genres: [35] },
  "saturday morning": { genres: [35, 10751] },
  "morning movie": { genres: [35, 10749] },
  "afternoon": { genres: [35, 12] },
  "sunday afternoon": { genres: [35, 18] },
  "evening": { genres: [53, 9648] },
  "friday night": { genres: [28, 35] },
  "saturday night": { genres: [28, 35] },
  "weekend": { genres: [28, 35] },
  "late night": { genres: [53, 27] },
  "midnight": { genres: [27, 53] },
  "3am": { genres: [27, 53] },
  "cant sleep": { genres: [53, 27] },
  "can't sleep": { genres: [53, 27] },
  "insomnia": { genres: [53, 27] },
  "cant sleep movie": { genres: [53, 9648] },
  "late night movie": { genres: [53, 27] },
  "night owl": { genres: [53, 27] },

  // WEATHER & SEASON
  "rainy day": { genres: [35, 18] },
  "rainy evening": { genres: [35, 18] },
  "rainy sunday": { genres: [35, 18] },
  "raining outside": { genres: [35, 18] },
  "cozy rainy day": { genres: [35, 10749] },
  "snowy day": { genres: [35, 10749] },
  "winter evening": { genres: [35, 10749] },
  "cold outside": { genres: [35, 10749] },
  "hot summer": { genres: [28, 12] },
  "summer movie": { genres: [28, 12] },
  "summer night": { genres: [35, 10749] },
  "christmas movie": { genres: [35, 10751] },
  "christmas": { genres: [35, 10751] },
  "halloween movie": { genres: [27] },
  "thanksgiving": { genres: [35, 10751] },
  "new year": { genres: [35, 10749] },

  // ENERGY STATE
  "no energy": { genres: [35, 10749] },
  "tired": { genres: [35, 10749] },
  "exhausted": { genres: [35, 10749] },
  "after hard day": { genres: [35, 10749] },
  "after work": { genres: [35, 10749] },
  "long day at work": { genres: [35, 10749] },
  "stressed out": { genres: [35, 10749] },
  "need to unwind": { genres: [35, 10749] },
  "want to relax": { genres: [35, 10749] },
  "comfort movie": { genres: [35, 10749] },
  "comfort watch": { genres: [35, 10749] },
  "background noise": { genres: [35] },
  "background movie": { genres: [35] },
  "half watching": { genres: [35] },
  "not paying full attention": { genres: [35] },
  "while eating": { genres: [35] },
  "lunch movie": { genres: [35] },
  "energetic": { genres: [28, 12] },
  "full of energy": { genres: [28, 12] },
  "workout motivation": { genres: [28, 12] },
  "before gym": { genres: [28, 12] },
  "pump me up": { genres: [28, 12] },

  // MENTAL STATE
  "bored": { genres: [28, 35] },
  "nothing to do": { genres: [28, 35] },
  "kill time": { genres: [28, 35] },
  "procrastinating": { genres: [35, 53] },
  "overthinking": { genres: [9648, 18] },
  "anxious": { genres: [35, 10749] },
  "depressed": { genres: [18, 35] },
  "lonely": { genres: [18, 35] },
  "alone": { genres: [18, 9648] },
  "solo movie night": { genres: [53, 9648] },
  "home alone": { genres: [53, 9648] },
  "want to escape": { genres: [12, 14] },
  "need distraction": { genres: [28, 35] },
  "overthink less": { genres: [35] },
  "need inspiration": { genres: [18, 36] },
  "feeling empty": { genres: [18] },
  "feeling lost": { genres: [18, 12] },
  "need motivation": { genres: [18, 36] },

  // SOCIAL
  "movie marathon": { genres: [28, 12] },
  "marathon": { genres: [28, 12] },
  "binge watch": { genres: [53, 9648] },
  "party": { genres: [35, 28] },
  "house party": { genres: [35, 28] },
  "drinking game": { genres: [35, 28] },
  "movie night": { genres: [53, 35] },
  "sleepover": { genres: [35, 27] },
  "sleepover movie": { genres: [35, 27] },
  "slumber party": { genres: [35, 27] },
  "first movie together": { genres: [10749, 35] },
  "new to cinema": { genres: [28, 12] },

  // FOOD-RELATED
  "pizza night": { genres: [35, 28] },
  "popcorn movie": { genres: [28, 35] },
  "junk food and movie": { genres: [28, 35] },
  "movie snacks": { genres: [28, 35] },
  "takeout night": { genres: [35, 28] },
  "delivery and movie": { genres: [35, 28] },

  // SPECIFIC VIBES
  "cozy autumn": { genres: [35, 9648] },
  "autumn vibes": { genres: [35, 9648] },
  "halloween vibes": { genres: [27, 9648] },
  "spooky season": { genres: [27] },
  "holiday vibes": { genres: [35, 10751] },
  "summer vibes": { genres: [12, 35] },
  "beach vibes": { genres: [35, 12] },
  "camping vibes": { genres: [12, 27] },
  "road trip vibes": { genres: [12, 35] },
  "monday blues": { genres: [35, 10749] },
  "end of week": { genres: [35, 28] },
  "sunday scaries": { genres: [35, 10749] },
  "lazy sunday": { genres: [35, 18] },
  "nothing on tv": { genres: [28, 35] },

  // ══════════════════════════════════════════════
  // STYLE & QUALITY
  // ══════════════════════════════════════════════
  "oscar winner": { genres: [18] },
  "oscar winners": { genres: [18] },
  "oscar nominated": { genres: [18] },
  "award winning": { genres: [18] },
  "critically acclaimed": { genres: [18] },
  "best picture": { genres: [18] },
  "academy award": { genres: [18] },
  "cannes winner": { genres: [18] },
  "indie": { genres: [18] },
  "indie movies": { genres: [18] },
  "independent film": { genres: [18] },
  "arthouse": { genres: [18] },
  "arthouse film": { genres: [18] },
  "cult classic": { genres: [18, 878] },
  "cult movie": { genres: [18, 878] },
  "cult following": { genres: [18, 878] },
  "underrated": { genres: [18, 9648] },
  "hidden gem": { genres: [18, 9648] },
  "hidden gems": { genres: [18, 9648] },
  "underrated gems": { genres: [18, 9648] },
  "overrated": { genres: [28, 18] },
  "blockbuster": { genres: [28, 12] },
  "summer blockbuster": { genres: [28, 12] },
  "popcorn flick": { genres: [28, 35] },
  "guilty pleasure": { genres: [35, 28] },
  "so bad its good": { genres: [35, 28] },
  "visually stunning": { genres: [14, 878] },
  "beautiful cinematography": { genres: [18, 14] },
  "aesthetic": { genres: [18, 14] },
  "slow burn": { genres: [18, 9648] },
  "slow paced": { genres: [18, 9648] },
  "fast paced": { genres: [28, 53] },
  "realistic": { genres: [18, 80] },
  "based on true story": { genres: [18, 36] },
  "true story": { genres: [18, 36] },
  "based on book": { genres: [18, 14] },
  "book adaptation": { genres: [18, 14] },
  "deep meaning": { genres: [18, 878] },
  "meaningful": { genres: [18] },

  // ══════════════════════════════════════════════
  // TOPICS & THEMES
  // ══════════════════════════════════════════════
  "space": { genres: [878] },
  "space movies": { genres: [878] },
  "space exploration": { genres: [878, 12] },
  "aliens": { genres: [878, 27] },
  "alien invasion": { genres: [878, 28] },
  "robots": { genres: [878] },
  "ai movies": { genres: [878] },
  "artificial intelligence": { genres: [878] },
  "time travel": { genres: [878, 12] },
  "parallel universe": { genres: [878, 9648] },
  "post apocalyptic": { genres: [878, 28] },
  "apocalypse": { genres: [878, 28] },
  "dystopia": { genres: [878, 18] },
  "dystopian": { genres: [878, 18] },
  "cyberpunk": { genres: [878, 28] },
  "virtual reality": { genres: [878] },
  "superpowers": { genres: [28, 12] },
  "magic": { genres: [14] },
  "dragons": { genres: [14, 12] },
  "medieval": { genres: [14, 28] },
  "mythology": { genres: [14, 36] },
  "greek mythology": { genres: [14, 36] },
  "vikings": { genres: [28, 36] },
  "pirates": { genres: [12, 28] },
  "survival": { genres: [28, 53] },
  "survival movies": { genres: [28, 53] },
  "wilderness survival": { genres: [12, 28] },
  "ocean": { genres: [12, 27] },
  "sea adventure": { genres: [12] },
  "underwater": { genres: [12, 878] },
  "jungle": { genres: [12, 27] },
  "desert": { genres: [12, 53] },
  "mountains": { genres: [12, 28] },
  "serial killer": { genres: [9648, 80] },
  "serial killers": { genres: [9648, 80] },
  "murder mystery": { genres: [9648, 80] },
  "whodunit": { genres: [9648] },
  "detective": { genres: [9648, 80] },
  "detective movies": { genres: [9648, 80] },
  "police": { genres: [80, 28] },
  "cop movies": { genres: [80, 28] },
  "prison": { genres: [18, 80] },
  "prison movies": { genres: [18, 80] },
  "court drama": { genres: [18, 80] },
  "legal drama": { genres: [18, 80] },
  "political": { genres: [18, 36] },
  "political thriller": { genres: [53, 18] },
  "conspiracy": { genres: [53, 9648] },
  "corruption": { genres: [18, 80] },
  "religion": { genres: [18, 36] },
  "faith": { genres: [18, 36] },
  "sports": { genres: [18] },
  "sports movies": { genres: [18] },
  "football": { genres: [18] },
  "boxing": { genres: [18, 28] },
  "boxing movies": { genres: [18, 28] },
  "sports drama": { genres: [18] },
  "music movies": { genres: [10402, 18] },
  "rock music": { genres: [10402, 18] },
  "hip hop": { genres: [10402, 18] },
  "dance": { genres: [10402, 35] },
  "dance movies": { genres: [10402, 35] },
  "concert film": { genres: [99, 10402] },
  "food": { genres: [35, 18] },
  "cooking": { genres: [35, 18] },
  "food documentary": { genres: [99] },
  "fashion": { genres: [18, 35] },
  "fashion documentary": { genres: [99] },
  "travel": { genres: [12, 35] },
  "travel movies": { genres: [12, 35] },
  "love triangle": { genres: [10749, 18] },
  "forbidden love": { genres: [10749, 18] },
  "unrequited love": { genres: [10749, 18] },
  "long distance": { genres: [10749, 18] },
  "second chance romance": { genres: [10749, 35] },
  "enemies to lovers": { genres: [10749, 35] },
  "friendship": { genres: [35, 18] },
  "growing up": { genres: [18, 35] },
  "loss": { genres: [18] },
  "grief": { genres: [18] },
  "death": { genres: [18] },
  "mental health": { genres: [18, 53] },
  "depression": { genres: [18] },
  "addiction": { genres: [18, 80] },
  "war drama": { genres: [10752, 18] },
  "wwii": { genres: [10752, 18] },
  "world war 2": { genres: [10752, 18] },
  "world war ii": { genres: [10752, 18] },
  "vietnam war": { genres: [10752, 18] },
  "cold war": { genres: [53, 36] },
  "nuclear": { genres: [53, 878] },
  "terrorism": { genres: [53, 28] },
  "heist film": { genres: [80, 53] },
  "bank robbery": { genres: [80, 28] },
  "true crime": { genres: [99, 80] },
  "nature documentary": { genres: [99] },
  "history documentary": { genres: [99, 36] },
  "crime documentary": { genres: [99, 80] },
  "war documentary": { genres: [99, 10752] },
  "music documentary": { genres: [99, 10402] },
  "food documentary": { genres: [99] },
  "sports documentary": { genres: [99] },
  "science documentary": { genres: [99, 878] },
  "anime": { search_query: "anime" },
  "anime movies": { search_query: "anime movie" },
  "anime film": { search_query: "anime movie" },
  "anime action": { search_query: "anime action" },
  "anime romance": { search_query: "anime romance" },
  "anime horror": { search_query: "anime horror" },
  "anime sci-fi": { search_query: "anime sci-fi" },
  "isekai": { search_query: "isekai anime" },
  "shonen": { search_query: "shonen anime" },
  "shoujo": { search_query: "shoujo anime" },
  "mecha": { search_query: "mecha anime" },
};

// ══════════════════════════════════════════════
// LOOKUP FUNCTION
// ══════════════════════════════════════════════

export function lookupPrompt(query) {
  const q = query.toLowerCase().trim();

  // 1. Exact match
  if (promptsDB[q]) return promptsDB[q];

  // 2. Partial match — query contains a key
  const keys = Object.keys(promptsDB);
  for (const key of keys) {
    if (q === key) return promptsDB[key];
  }

  // 3. Key is contained in query (e.g. "some nolan films" contains "nolan")
  for (const key of keys) {
    if (key.length > 3 && q.includes(key)) {
      return promptsDB[key];
    }
  }

  // 4. Query words match key words
  const qWords = q.split(/\s+/);
  for (const key of keys) {
    const kWords = key.split(/\s+/);
    if (kWords.length >= 2 && kWords.every(w => q.includes(w))) {
      return promptsDB[key];
    }
  }

  return null;
}
